[project]
name = "repl-nix-workspace"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "fastapi>=0.124.4",
    "httpx>=0.28.1",
    "playwright>=1.57.0",
    "tenacity>=9.1.2",
    "uvicorn>=0.38.0",
]
